### ISSUE TITLE
Validate backend commands

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend#12]
Make sure noise and average pixel output the correct values

**Comment by jbpagliuco** [comment]
@jonthaler What's the formula for the second moment for an image?

**Comment by jonthaler** [comment]
The second moment, x2, is the mean of the square of the deviation of a set of numbers, {xi}, from their mean, xav.

That is, x2  = Sum((xi-xav)**2)/N.
To avoid scanning over the data twice, it can be rewritten, using xav =Sum(xi)/N, 
  as x2 = Sum(xi**2)/N - (Sum(xi))/N)**2.
However this is more susceptible to numerical errors when x2 << xav**2.

You want to display the standard deviation (usually denoted by greek sigma) which is Sqrt(x2).

Jon
