### ISSUE TITLE
Hot pixel display has an 0.5 pixel offset

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend#33]
I issued this command: `hot_pixel ffview 1200 (rect 1444 2522 1459 2544)`
The result is shown in the attached image (zoomed in as far as possible).
   
Using Firefly popup window coordinates (which show fractional values):
The center of the lower left  “hot” circle is at: (1444.0, 2522.0)
The center of the upper right “hot” circle is at: (1459.0, 2544.0)
The corners of the drawn rect are: (1444.0, 2522.0) and  (1460.0, 2545.0)

The problem:
The “hot” pixel display is offset with respect to the region of interest.
There is an 0.5 pixel error (in both x and y) where the “hot” circles are drawn.  

The reason:
The left-most pixel in the image spans x = 0.0 to 1.0.  Similarly, the bottom-most pixel spans y = 0.0 to 1.0.  Therefore, the center of the lower-left pixel is at (0.5, 0.5).

The solution:
You need to add (0.5, 0.5) to the locations of “hot” circles (and to any other display of pixel locations) in order to center them on the pixels.
The rect is drawn correctly, because the boundary of the region of interest is at pixel edges, not pixel centers.

![hot_pixel](https://cloud.githubusercontent.com/assets/14808549/26613819/405aa4ce-4582-11e7-9c06-c4975471af74.jpeg)

**Comment by weiren2** [comment]
Fixed in d7f0d96. Using circles instead of points is a good way to control the scaling. Now the points look like this:
![image](https://cloud.githubusercontent.com/assets/6765243/26657806/c9f47b2a-462b-11e7-867d-a69a787ca7a4.png)


Reopen the issue if there are any more related bugs.
