### ISSUE TITLE
Set image repo

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend#37]
Set the uv image repo via the command line

**Comment by jbpagliuco** [comment]
@jonthaler the command is called "set_setting", with parameters "setting_name" and "new_value". Leaving "new_value" empty uses the default setting value

**Comment by jonthaler** [comment]
Joe,

Thanks for this.  I will document the “set_setting” command and mention that only the “imageRepo” keyword is implemented.  Is there documentation on the developer’s side?

Let me know when “graph_noise” works (is that still the name, or has it become “table_noise”), and I’ll document that also.

Jon

**Comment by jonthaler** [comment]
Question:  Is the value always a string?  If a numerical value is wanted, how will it be parsed?

> Joe,
> 
> Thanks for this.  I will document the “set_setting” command and mention that only the “imageRepo” keyword is implemented.  Is there documentation on the developer’s side?
> 
> Let me know when “graph_noise” works (is that still the name, or has it become “table_noise”), and I’ll document that also.
> 
> Jon
>

**Comment by jonthaler** [comment]
Take a look and comment. https://github.com/lsst-camera-visualization/frontend/wiki#set_setting <https://github.com/lsst-camera-visualization/frontend/wiki#set_setting>

> Joe,
> 
> Thanks for this.  I will document the “set_setting” command and mention that only the “imageRepo” keyword is implemented.  Is there documentation on the developer’s side?
> 
> Let me know when “graph_noise” works (is that still the name, or has it become “table_noise”), and I’ll document that also.
> 
> Jon
>
